from routes.Customers import customers
from routes.Flights import flights
from routes.Admins import admins
from routes.Airplanecarriers import airplanecarriers
from routes.Airplanes import airplanes
from routes.Flights_booked import flightsbooked
from routes.BoardingPasses import boardingpasses
from routes.Airports import airports
from routes.Seats import seats
